import java.math.BigDecimal;

public class Main {

    public static void main(String[] args) {
        System.out.println("=".repeat(50));
        System.out.println("Curso Completo de Algoritmos e Logica de Programacao");
        System.out.println("educandoweb.com.br");
        System.out.println("Prof. Dr. Nelio Alves");
        System.out.println("Capitulo: Estrutura sequencial");
        System.out.println("Exercicios - PARTE 1");
        System.out.println("=".repeat(50));
        System.out.println();

        System.out.println("-".repeat(50));
        System.out.println("Problema TERRENO");
        System.out.println("-".repeat(50));
        System.out.println("Exemplo 1:");
        Terreno t1 = new Terreno();
        t1.setLarguraTerreno(10.0);
        t1.setComprimentoTerreno(30.0);
        t1.setValorMetroQuadrado(new BigDecimal("200.00"));
        System.out.printf("Digite a largura do terreno: %.1f%n", t1.getLarguraTerreno());
        System.out.printf("Digite o comprimento do terreno: %.1f%n", t1.getComprimentoTerreno());
        System.out.printf("Digite o valor do metro quadrado: %.2f%n", t1.getValorMetroQuadrado());
        System.out.printf("Area do terreno = %.2f%n", t1.getArea());
        System.out.printf("Preco do terreno = %.2f%n", t1.getPreco());
        System.out.println();
        System.out.println("Exemplo 2:");
        Terreno t2 = new Terreno();
        t2.setLarguraTerreno(12.0);
        t2.setComprimentoTerreno(20.0);
        t2.setValorMetroQuadrado(new BigDecimal("150.00"));
        System.out.printf("Digite a largura do terreno: %.1f%n", t2.getLarguraTerreno());
        System.out.printf("Digite o comprimento do terreno: %.1f%n", t2.getComprimentoTerreno());
        System.out.printf("Digite o valor do metro quadrado: %.2f%n", t2.getValorMetroQuadrado());
        System.out.printf("Area do terreno = %.2f%n", t2.getArea());
        System.out.printf("Preco do terreno = %.2f%n", t2.getPreco());
        System.out.println();

        System.out.println("-".repeat(50));
        System.out.println("Problema RETANGULO");
        System.out.println("-".repeat(50));
        System.out.println("Exemplo 1:");
        Retangulo r1 = new Retangulo();
        r1.setBaseRetangulo(4.0);
        r1.setAlturaRetangulo(5.0);
        System.out.printf("Base do retangulo: %.1f%n", r1.getBaseRetangulo());
        System.out.printf("Altura do retangulo: %.1f%n", r1.getAlturaRetangulo());
        System.out.printf("AREA = %.4f%n", r1.getArea());
        System.out.printf("PERIMETRO = %.4f%n", r1.getPerimetro());
        System.out.printf("DIAGONAL = %.4f%n", r1.getDiagonal());
        System.out.println();
        System.out.println("Exemplo 2:");
        Retangulo r2 = new Retangulo();
        r2.setBaseRetangulo(10.3);
        r2.setAlturaRetangulo(13.1);
        System.out.printf("Base do retangulo: %.1f%n", r2.getBaseRetangulo());
        System.out.printf("Altura do retangulo: %.1f%n", r2.getAlturaRetangulo());
        System.out.printf("AREA = %.4f%n", r2.getArea());
        System.out.printf("PERIMETRO = %.4f%n", r2.getPerimetro());
        System.out.printf("DIAGONAL = %.4f%n", r2.getDiagonal());
        System.out.println();

        System.out.println("-".repeat(50));
        System.out.println("Problema IDADES");
        System.out.println("-".repeat(50));
        Idades id = new Idades();
        id.setNomePrimeiraPessoa("Maria Silva");
        id.setIdadePrimeiraPessoa(19);
        id.setNomeSegundaPessoa("Joao Melo");
        id.setIdadeSegundaPessoa(20);
        System.out.println("Dados da primeira pessoa:");
        System.out.printf("Nome: %s%n", id.getNomePrimeiraPessoa());
        System.out.printf("Idade: %d%n", id.getIdadePrimeiraPessoa());
        System.out.println("Dados da segunda pessoa:");
        System.out.printf("Nome: %s%n", id.getNomeSegundaPessoa());
        System.out.printf("Idade: %d%n", id.getIdadeSegundaPessoa());
        System.out.printf("A idade media de %s e %s e de %.1f anos%n",
                id.getNomePrimeiraPessoa(), id.getNomeSegundaPessoa(), id.getMediaIdade());
        System.out.println();

        System.out.println("-".repeat(50));
        System.out.println("Problema SOMA");
        System.out.println("-".repeat(50));
        System.out.println("Exemplo 1:");
        Soma s1 = new Soma();
        s1.setX(8);
        s1.setY(10);
        System.out.printf("Digite o valor de X: %d%n", s1.getX());
        System.out.printf("Digite o valor de Y: %d%n", s1.getY());
        System.out.printf("SOMA = %d%n", s1.getTotal());
        System.out.println();
        System.out.println("Exemplo 2:");
        Soma s2 = new Soma();
        s2.setX(12);
        s2.setY(31);
        System.out.printf("Digite o valor de X: %d%n", s2.getX());
        System.out.printf("Digite o valor de Y: %d%n", s2.getY());
        System.out.printf("SOMA = %d%n", s2.getTotal());
        System.out.println();

        System.out.println("-".repeat(50));
        System.out.println("Problema TROCO");
        System.out.println("-".repeat(50));
        System.out.println("Exemplo 1:");
        Troco tr1 = new Troco();
        tr1.setPrecoUnitario(new BigDecimal("8.00"));
        tr1.setQtdComprada(2);
        tr1.setDinheiroRecebido(new BigDecimal("20.00"));
        System.out.printf("Preco unitario do produto: %.2f%n", tr1.getPrecoUnitario());
        System.out.printf("Quantidade comprada: %d%n", tr1.getQtdComprada());
        System.out.printf("Dinheiro recebido: %.2f%n", tr1.getDinheiroRecebido());
        System.out.printf("TROCO = %.2f%n", tr1.getTotal());
        System.out.println();
        System.out.println("Exemplo 2:");
        Troco tr2 = new Troco();
        tr2.setPrecoUnitario(new BigDecimal("30.00"));
        tr2.setQtdComprada(3);
        tr2.setDinheiroRecebido(new BigDecimal("100.00"));
        System.out.printf("Preco unitario do produto: %.2f%n", tr2.getPrecoUnitario());
        System.out.printf("Quantidade comprada: %d%n", tr2.getQtdComprada());
        System.out.printf("Dinheiro recebido: %.2f%n", tr2.getDinheiroRecebido());
        System.out.printf("TROCO = %.2f%n", tr2.getTotal());
        System.out.println();

        System.out.println("-".repeat(50));
        System.out.println("Problema CIRCULO");
        System.out.println("-".repeat(50));
        System.out.println("Exemplo 1:");
        Circulo c1 = new Circulo();
        c1.setRaio(2.0);
        System.out.printf("Digite o valor do raio do circulo: %.1f%n", c1.getRaio());
        System.out.printf("AREA = %.3f%n", c1.getArea());
        System.out.println();
        System.out.println("Exemplo 2:");
        Circulo c2 = new Circulo();
        c2.setRaio(13.2);
        System.out.printf("Digite o valor do raio do circulo: %.1f%n", c2.getRaio());
        System.out.printf("AREA = %.3f%n", c2.getArea());
        System.out.println();

        System.out.println("-".repeat(50));
        System.out.println("Problema PAGAMENTO");
        System.out.println("-".repeat(50));
        System.out.println("Exemplo 1:");
        Pagamento p1 = new Pagamento();
        p1.setNome("Joao Silva");
        p1.setValorHora(new BigDecimal("50.00"));
        p1.setHorasTrabalhadas(60.0);
        System.out.printf("Nome: %s%n", p1.getNome());
        System.out.printf("Valor por hora: %.2f%n", p1.getValorHora());
        System.out.printf("Horas trabalhadas: %.0f%n", p1.getHorasTrabalhadas());
        System.out.printf("O pagamento para %s deve ser %.2f%n", p1.getNome(), p1.getTotal());
        System.out.println();
        System.out.println("Exemplo 2:");
        Pagamento p2 = new Pagamento();
        p2.setNome("Maria Dias");
        p2.setValorHora(new BigDecimal("60.00"));
        p2.setHorasTrabalhadas(100.0);
        System.out.printf("Nome: %s%n", p2.getNome());
        System.out.printf("Valor por hora: %.2f%n", p2.getValorHora());
        System.out.printf("Horas trabalhadas: %.0f%n", p2.getHorasTrabalhadas());
        System.out.printf("O pagamento para %s deve ser %.2f%n", p2.getNome(), p2.getTotal());
        System.out.println();

        System.out.println("-".repeat(50));
        System.out.println("Problema CONSUMO");
        System.out.println("-".repeat(50));
        System.out.println("Exemplo 1:");
        Consumo con1 = new Consumo();
        con1.setDistanciaPercorrida(500.0);
        con1.setCombustivelGasto(38.5);
        System.out.printf("Distancia percorrida: %.0f%n", con1.getDistanciaPercorrida());
        System.out.printf("Combustivel gasto: %.1f%n", con1.getCombustivelGasto());
        System.out.printf("Consumo medio = %.3f%n", con1.getConsumoMedio());
        System.out.println();
        System.out.println("Exemplo 2:");
        Consumo con2 = new Consumo();
        con2.setDistanciaPercorrida(1108.0);
        con2.setCombustivelGasto(71.4);
        System.out.printf("Distancia percorrida: %.0f%n", con2.getDistanciaPercorrida());
        System.out.printf("Combustivel gasto: %.1f%n", con2.getCombustivelGasto());
        System.out.printf("Consumo medio = %.3f%n", con2.getConsumoMedio());
        System.out.println();

        System.out.println("-".repeat(50));
        System.out.println("Problema MEDIDAS");
        System.out.println("-".repeat(50));
        System.out.println("Exemplo 1:");
        Medidas m1 = new Medidas();
        m1.setA(4.0);
        m1.setB(3.5);
        m1.setC(5.2);
        System.out.printf("Digite a medida A: %.1f%n", m1.getA());
        System.out.printf("Digite a medida B: %.1f%n", m1.getB());
        System.out.printf("Digite a medida C: %.1f%n", m1.getC());
        System.out.printf("AREA DO QUADRADO = %.4f%n", m1.getAreaQuadrado());
        System.out.printf("AREA DO TRIANGULO = %.4f%n", m1.getAreaTriangulo());
        System.out.printf("AREA DO TRAPEZIO = %.4f%n", m1.getAreaTrapezio());
        System.out.println();
        System.out.println("Exemplo 2:");
        Medidas m2 = new Medidas();
        m2.setA(7.13);
        m2.setB(8.05);
        m2.setC(11.912);
        System.out.printf("Digite a medida A: %.2f%n", m2.getA());
        System.out.printf("Digite a medida B: %.2f%n", m2.getB());
        System.out.printf("Digite a medida C: %.3f%n", m2.getC());
        System.out.printf("AREA DO QUADRADO = %.4f%n", m2.getAreaQuadrado());
        System.out.printf("AREA DO TRIANGULO = %.4f%n", m2.getAreaTriangulo());
        System.out.printf("AREA DO TRAPEZIO = %.4f%n", m2.getAreaTrapezio());
        System.out.println();

        System.out.println("-".repeat(50));
        System.out.println("Problema DURACAO");
        System.out.println("-".repeat(50));
        System.out.println("Exemplo 1:");
        Duracao d1 = new Duracao();
        d1.setDuracao(300);
        System.out.printf("Digite a duracao em segundos: %d%n", d1.getDuracao());
        System.out.printf("%d:%d:%d%n", d1.getHoras(), d1.getMinutos(), d1.getSegundos());
        System.out.println();
        System.out.println("Exemplo 2:");
        Duracao d2 = new Duracao();
        d2.setDuracao(12506);
        System.out.printf("Digite a duracao em segundos: %d%n", d2.getDuracao());
        System.out.printf("%d:%d:%d%n", d2.getHoras(), d2.getMinutos(), d2.getSegundos());
        System.out.println();
        System.out.println("Exemplo 3:");
        Duracao d3 = new Duracao();
        d3.setDuracao(140811);
        System.out.printf("Digite a duracao em segundos: %d%n", d3.getDuracao());
        System.out.printf("%d:%d:%d%n", d3.getHoras(), d3.getMinutos(), d3.getSegundos());
        System.out.println();

        System.out.println("=".repeat(50));
        System.out.println("TODOS OS TESTES EXECUTADOS COM SUCESSO!");
        System.out.println("=".repeat(50));
    }
}