import java.math.BigDecimal;
import java.util.List;

public class Main {
    public static void main(String[] args) {
        System.out.println("=".repeat(50));
        System.out.println("Curso Completo de Algoritmos e Logica de Programacao");
        System.out.println("educandoweb.com.br");
        System.out.println("Prof. Dr. Nelio Alves");
        System.out.println("Capitulo: Estrutura sequencial");
        System.out.println("Exercicios - PARTE 1");
        System.out.println("=".repeat(50));
        System.out.println();

        System.out.println("-".repeat(50));
        System.out.println("Problema TERRENO");
        System.out.println("-".repeat(50));
        System.out.println("Exemplo 1:");
        Terreno t1 = new Terreno();
        t1.setLarguraTerreno(10.0);
        t1.setComprimentoTerreno(30.0);
        t1.setValorMetroQuadrado(new BigDecimal("200.00"));
        System.out.printf("Digite a largura do terreno: %.1f%n", t1.getLarguraTerreno());
        System.out.printf("Digite o comprimento do terreno: %.1f%n", t1.getComprimentoTerreno());
        System.out.printf("Digite o valor do metro quadrado: %.2f%n", t1.getValorMetroQuadrado());
        System.out.printf("Area do terreno = %.2f%n", t1.getArea());
        System.out.printf("Preco do terreno = %.2f%n", t1.getPreco());
        System.out.println();
        System.out.println("Exemplo 2:");
        Terreno t2 = new Terreno();
        t2.setLarguraTerreno(12.0);
        t2.setComprimentoTerreno(20.0);
        t2.setValorMetroQuadrado(new BigDecimal("150.00"));
        System.out.printf("Digite a largura do terreno: %.1f%n", t2.getLarguraTerreno());
        System.out.printf("Digite o comprimento do terreno: %.1f%n", t2.getComprimentoTerreno());
        System.out.printf("Digite o valor do metro quadrado: %.2f%n", t2.getValorMetroQuadrado());
        System.out.printf("Area do terreno = %.2f%n", t2.getArea());
        System.out.printf("Preco do terreno = %.2f%n", t2.getPreco());
        System.out.println();

        System.out.println("-".repeat(50));
        System.out.println("Problema RETANGULO");
        System.out.println("-".repeat(50));
        System.out.println("Exemplo 1:");
        Retangulo r1 = new Retangulo();
        r1.setBaseRetangulo(4.0);
        r1.setAlturaRetangulo(5.0);
        System.out.printf("Base do retangulo: %.1f%n", r1.getBaseRetangulo());
        System.out.printf("Altura do retangulo: %.1f%n", r1.getAlturaRetangulo());
        System.out.printf("AREA = %.4f%n", r1.getArea());
        System.out.printf("PERIMETRO = %.4f%n", r1.getPerimetro());
        System.out.printf("DIAGONAL = %.4f%n", r1.getDiagonal());
        System.out.println();
        System.out.println("Exemplo 2:");
        Retangulo r2 = new Retangulo();
        r2.setBaseRetangulo(10.3);
        r2.setAlturaRetangulo(13.1);
        System.out.printf("Base do retangulo: %.1f%n", r2.getBaseRetangulo());
        System.out.printf("Altura do retangulo: %.1f%n", r2.getAlturaRetangulo());
        System.out.printf("AREA = %.4f%n", r2.getArea());
        System.out.printf("PERIMETRO = %.4f%n", r2.getPerimetro());
        System.out.printf("DIAGONAL = %.4f%n", r2.getDiagonal());
        System.out.println();

        System.out.println("-".repeat(50));
        System.out.println("Problema IDADES");
        System.out.println("-".repeat(50));
        Idades id = new Idades();
        id.setNomePrimeiraPessoa("Maria Silva");
        id.setIdadePrimeiraPessoa(19);
        id.setNomeSegundaPessoa("Joao Melo");
        id.setIdadeSegundaPessoa(20);
        System.out.println("Dados da primeira pessoa:");
        System.out.printf("Nome: %s%n", id.getNomePrimeiraPessoa());
        System.out.printf("Idade: %d%n", id.getIdadePrimeiraPessoa());
        System.out.println("Dados da segunda pessoa:");
        System.out.printf("Nome: %s%n", id.getNomeSegundaPessoa());
        System.out.printf("Idade: %d%n", id.getIdadeSegundaPessoa());
        System.out.printf("A idade media de %s e %s e de %.1f anos%n",
                id.getNomePrimeiraPessoa(), id.getNomeSegundaPessoa(), id.getMediaIdade());
        System.out.println();

        System.out.println("-".repeat(50));
        System.out.println("Problema SOMA");
        System.out.println("-".repeat(50));
        System.out.println("Exemplo 1:");
        Soma s1 = new Soma();
        s1.setX(8);
        s1.setY(10);
        System.out.printf("Digite o valor de X: %d%n", s1.getX());
        System.out.printf("Digite o valor de Y: %d%n", s1.getY());
        System.out.printf("SOMA = %d%n", s1.getTotal());
        System.out.println();
        System.out.println("Exemplo 2:");
        Soma s2 = new Soma();
        s2.setX(12);
        s2.setY(31);
        System.out.printf("Digite o valor de X: %d%n", s2.getX());
        System.out.printf("Digite o valor de Y: %d%n", s2.getY());
        System.out.printf("SOMA = %d%n", s2.getTotal());
        System.out.println();

        System.out.println("-".repeat(50));
        System.out.println("Problema TROCO");
        System.out.println("-".repeat(50));
        System.out.println("Exemplo 1:");
        Troco tr1 = new Troco();
        tr1.setPrecoUnitario(new BigDecimal("8.00"));
        tr1.setQtdComprada(2);
        tr1.setDinheiroRecebido(new BigDecimal("20.00"));
        System.out.printf("Preco unitario do produto: %.2f%n", tr1.getPrecoUnitario());
        System.out.printf("Quantidade comprada: %d%n", tr1.getQtdComprada());
        System.out.printf("Dinheiro recebido: %.2f%n", tr1.getDinheiroRecebido());
        System.out.printf("TROCO = %.2f%n", tr1.getTotal());
        System.out.println();
        System.out.println("Exemplo 2:");
        Troco tr2 = new Troco();
        tr2.setPrecoUnitario(new BigDecimal("30.00"));
        tr2.setQtdComprada(3);
        tr2.setDinheiroRecebido(new BigDecimal("100.00"));
        System.out.printf("Preco unitario do produto: %.2f%n", tr2.getPrecoUnitario());
        System.out.printf("Quantidade comprada: %d%n", tr2.getQtdComprada());
        System.out.printf("Dinheiro recebido: %.2f%n", tr2.getDinheiroRecebido());
        System.out.printf("TROCO = %.2f%n", tr2.getTotal());
        System.out.println();

        System.out.println("-".repeat(50));
        System.out.println("Problema CIRCULO");
        System.out.println("-".repeat(50));
        System.out.println("Exemplo 1:");
        Circulo c1 = new Circulo();
        c1.setRaio(2.0);
        System.out.printf("Digite o valor do raio do circulo: %.1f%n", c1.getRaio());
        System.out.printf("AREA = %.3f%n", c1.getArea());
        System.out.println();
        System.out.println("Exemplo 2:");
        Circulo c2 = new Circulo();
        c2.setRaio(13.2);
        System.out.printf("Digite o valor do raio do circulo: %.1f%n", c2.getRaio());
        System.out.printf("AREA = %.3f%n", c2.getArea());
        System.out.println();

        System.out.println("-".repeat(50));
        System.out.println("Problema PAGAMENTO");
        System.out.println("-".repeat(50));
        System.out.println("Exemplo 1:");
        Pagamento p1 = new Pagamento();
        p1.setNome("Joao Silva");
        p1.setValorHora(new BigDecimal("50.00"));
        p1.setHorasTrabalhadas(60.0);
        System.out.printf("Nome: %s%n", p1.getNome());
        System.out.printf("Valor por hora: %.2f%n", p1.getValorHora());
        System.out.printf("Horas trabalhadas: %.0f%n", p1.getHorasTrabalhadas());
        System.out.printf("O pagamento para %s deve ser %.2f%n", p1.getNome(), p1.getTotal());
        System.out.println();
        System.out.println("Exemplo 2:");
        Pagamento p2 = new Pagamento();
        p2.setNome("Maria Dias");
        p2.setValorHora(new BigDecimal("60.00"));
        p2.setHorasTrabalhadas(100.0);
        System.out.printf("Nome: %s%n", p2.getNome());
        System.out.printf("Valor por hora: %.2f%n", p2.getValorHora());
        System.out.printf("Horas trabalhadas: %.0f%n", p2.getHorasTrabalhadas());
        System.out.printf("O pagamento para %s deve ser %.2f%n", p2.getNome(), p2.getTotal());
        System.out.println();

        System.out.println("-".repeat(50));
        System.out.println("Problema CONSUMO");
        System.out.println("-".repeat(50));
        System.out.println("Exemplo 1:");
        Consumo con1 = new Consumo();
        con1.setDistanciaPercorrida(500.0);
        con1.setCombustivelGasto(38.5);
        System.out.printf("Distancia percorrida: %.0f%n", con1.getDistanciaPercorrida());
        System.out.printf("Combustivel gasto: %.1f%n", con1.getCombustivelGasto());
        System.out.printf("Consumo medio = %.3f%n", con1.getConsumoMedio());
        System.out.println();
        System.out.println("Exemplo 2:");
        Consumo con2 = new Consumo();
        con2.setDistanciaPercorrida(1108.0);
        con2.setCombustivelGasto(71.4);
        System.out.printf("Distancia percorrida: %.0f%n", con2.getDistanciaPercorrida());
        System.out.printf("Combustivel gasto: %.1f%n", con2.getCombustivelGasto());
        System.out.printf("Consumo medio = %.3f%n", con2.getConsumoMedio());
        System.out.println();

        System.out.println("-".repeat(50));
        System.out.println("Problema MEDIDAS");
        System.out.println("-".repeat(50));
        System.out.println("Exemplo 1:");
        Medidas m1 = new Medidas();
        m1.setA(4.0);
        m1.setB(3.5);
        m1.setC(5.2);
        System.out.printf("Digite a medida A: %.1f%n", m1.getA());
        System.out.printf("Digite a medida B: %.1f%n", m1.getB());
        System.out.printf("Digite a medida C: %.1f%n", m1.getC());
        System.out.printf("AREA DO QUADRADO = %.4f%n", m1.getAreaQuadrado());
        System.out.printf("AREA DO TRIANGULO = %.4f%n", m1.getAreaTriangulo());
        System.out.printf("AREA DO TRAPEZIO = %.4f%n", m1.getAreaTrapezio());
        System.out.println();
        System.out.println("Exemplo 2:");
        Medidas m2 = new Medidas();
        m2.setA(7.13);
        m2.setB(8.05);
        m2.setC(11.912);
        System.out.printf("Digite a medida A: %.2f%n", m2.getA());
        System.out.printf("Digite a medida B: %.2f%n", m2.getB());
        System.out.printf("Digite a medida C: %.3f%n", m2.getC());
        System.out.printf("AREA DO QUADRADO = %.4f%n", m2.getAreaQuadrado());
        System.out.printf("AREA DO TRIANGULO = %.4f%n", m2.getAreaTriangulo());
        System.out.printf("AREA DO TRAPEZIO = %.4f%n", m2.getAreaTrapezio());
        System.out.println();

        System.out.println("-".repeat(50));
        System.out.println("Problema DURACAO");
        System.out.println("-".repeat(50));
        System.out.println("Exemplo 1:");
        Duracao d1 = new Duracao();
        d1.setDuracao(300);
        System.out.printf("Digite a duracao em segundos: %d%n", d1.getDuracao());
        System.out.printf("%d:%d:%d%n", d1.getHoras(), d1.getMinutos(), d1.getSegundos());
        System.out.println();
        System.out.println("Exemplo 2:");
        Duracao d2 = new Duracao();
        d2.setDuracao(12506);
        System.out.printf("Digite a duracao em segundos: %d%n", d2.getDuracao());
        System.out.printf("%d:%d:%d%n", d2.getHoras(), d2.getMinutos(), d2.getSegundos());
        System.out.println();
        System.out.println("Exemplo 3:");
        Duracao d3 = new Duracao();
        d3.setDuracao(140811);
        System.out.printf("Digite a duracao em segundos: %d%n", d3.getDuracao());
        System.out.printf("%d:%d:%d%n", d3.getHoras(), d3.getMinutos(), d3.getSegundos());
        System.out.println();

        System.out.println("=".repeat(50));
        System.out.println("Curso Completo de Algoritmos e Logica de Programacao");
        System.out.println("educandoweb.com.br");
        System.out.println("Prof. Dr. Nelio Alves");
        System.out.println("Capitulo: Estrutura condicional");
        System.out.println("Exercicios - PARTE 2");
        System.out.println("=".repeat(50));
        System.out.println();

        System.out.println("-".repeat(50));
        System.out.println("Problema NOTAS");
        System.out.println("-".repeat(50));
        System.out.println("Exemplo 1:");
        Notas n1 = new Notas();
        n1.setNota1(45.5);
        n1.setNota2(31.3);
        System.out.printf("Digite a primeira nota: %.1f%n", n1.getNota1());
        System.out.printf("Digite a segunda nota: %.1f%n", n1.getNota2());
        System.out.printf("NOTA FINAL = %.1f%n", n1.getNotaFinal());
        if (n1.isReprovado()) {
            System.out.println("REPROVADO");
        }
        System.out.println();
        System.out.println("Exemplo 2:");
        Notas n2 = new Notas();
        n2.setNota1(34.0);
        n2.setNota2(23.5);
        System.out.printf("Digite a primeira nota: %.1f%n", n2.getNota1());
        System.out.printf("Digite a segunda nota: %.1f%n", n2.getNota2());
        System.out.printf("NOTA FINAL = %.1f%n", n2.getNotaFinal());
        if (n2.isReprovado()) {
            System.out.println("REPROVADO");
        }
        System.out.println();

        System.out.println("-".repeat(50));
        System.out.println("Problema BASKARA");
        System.out.println("-".repeat(50));
        System.out.println("Exemplo 1:");
        Baskara b1 = new Baskara();
        b1.setA(1.0);
        b1.setB(0.0);
        b1.setC(-9.0);
        System.out.printf("Coeficiente a: %.1f%n", b1.getA());
        System.out.printf("Coeficiente b: %.1f%n", b1.getB());
        System.out.printf("Coeficiente c: %.1f%n", b1.getC());
        b1.calcular();
        System.out.println();
        System.out.println();
        System.out.println("Exemplo 2:");
        Baskara b2 = new Baskara();
        b2.setA(2.0);
        b2.setB(-4.5);
        b2.setC(1.7);
        System.out.printf("Coeficiente a: %.1f%n", b2.getA());
        System.out.printf("Coeficiente b: %.1f%n", b2.getB());
        System.out.printf("Coeficiente c: %.1f%n", b2.getC());
        b2.calcular();
        System.out.println();
        System.out.println();
        System.out.println("Exemplo 3:");
        Baskara b3 = new Baskara();
        b3.setA(1.0);
        b3.setB(3.0);
        b3.setC(4.0);
        System.out.printf("Coeficiente a: %.1f%n", b3.getA());
        System.out.printf("Coeficiente b: %.1f%n", b3.getB());
        System.out.printf("Coeficiente c: %.1f%n", b3.getC());
        b3.calcular();
        System.out.println();
        System.out.println();

        System.out.println("-".repeat(50));
        System.out.println("Problema MENOR_DE_TRES");
        System.out.println("-".repeat(50));
        System.out.println("Exemplo 1:");
        MenorDeTres mdt1 = new MenorDeTres();
        mdt1.setNum1(7);
        mdt1.setNum2(3);
        mdt1.setNum3(8);
        System.out.printf("Primeiro valor: %d%n", mdt1.getNum1());
        System.out.printf("Segundo valor: %d%n", mdt1.getNum2());
        System.out.printf("Terceiro valor: %d%n", mdt1.getNum3());
        System.out.printf("MENOR = %d%n", mdt1.getMenor());
        System.out.println();
        System.out.println("Exemplo 2:");
        MenorDeTres mdt2 = new MenorDeTres();
        mdt2.setNum1(5);
        mdt2.setNum2(12);
        mdt2.setNum3(5);
        System.out.printf("Primeiro valor: %d%n", mdt2.getNum1());
        System.out.printf("Segundo valor: %d%n", mdt2.getNum2());
        System.out.printf("Terceiro valor: %d%n", mdt2.getNum3());
        System.out.printf("MENOR = %d%n", mdt2.getMenor());
        System.out.println();
        System.out.println("Exemplo 3:");
        MenorDeTres mdt3 = new MenorDeTres();
        mdt3.setNum1(9);
        mdt3.setNum2(9);
        mdt3.setNum3(9);
        System.out.printf("Primeiro valor: %d%n", mdt3.getNum1());
        System.out.printf("Segundo valor: %d%n", mdt3.getNum2());
        System.out.printf("Terceiro valor: %d%n", mdt3.getNum3());
        System.out.printf("MENOR = %d%n", mdt3.getMenor());
        System.out.println();

        System.out.println("-".repeat(50));
        System.out.println("Problema OPERADORA");
        System.out.println("-".repeat(50));
        System.out.println("Exemplo 1:");
        Operadora op1 = new Operadora(new BigDecimal("50.00"), 100, new BigDecimal("2.00"));
        op1.setTotalMinutoUtilizado(22);
        System.out.printf("Digite a quantidade de minutos: %d%n", op1.getTotalMinutoUtilizado());
        System.out.printf("Valor a pagar: R$ %.2f%n", op1.getTotal());
        System.out.println();
        System.out.println("Exemplo 2:");
        Operadora op2 = new Operadora(new BigDecimal("50.00"), 100, new BigDecimal("2.00"));
        op2.setTotalMinutoUtilizado(103);
        System.out.printf("Digite a quantidade de minutos: %d%n", op2.getTotalMinutoUtilizado());
        System.out.printf("Valor a pagar: R$ %.2f%n", op2.getTotal());
        System.out.println();

        System.out.println("-".repeat(50));
        System.out.println("Problema TROCO_VERIFICADO");
        System.out.println("-".repeat(50));
        System.out.println("Exemplo 1:");
        TrocoVerificado tv1 = new TrocoVerificado();
        tv1.setPrecoUnitario(new BigDecimal("8.00"));
        tv1.setQtdComprada(2);
        tv1.setDinheiroRecebido(new BigDecimal("20.00"));
        System.out.printf("Preco unitario do produto: %.2f%n", tv1.getPrecoUnitario());
        System.out.printf("Quantidade comprada: %d%n", tv1.getQtdComprada());
        System.out.printf("Dinheiro recebido: %.2f%n", tv1.getDinheiroRecebido());
        tv1.calcular();
        System.out.println();
        System.out.println();
        System.out.println("Exemplo 2:");
        TrocoVerificado tv2 = new TrocoVerificado();
        tv2.setPrecoUnitario(new BigDecimal("30.00"));
        tv2.setQtdComprada(3);
        tv2.setDinheiroRecebido(new BigDecimal("70.00"));
        System.out.printf("Preco unitario do produto: %.2f%n", tv2.getPrecoUnitario());
        System.out.printf("Quantidade comprada: %d%n", tv2.getQtdComprada());
        System.out.printf("Dinheiro recebido: %.2f%n", tv2.getDinheiroRecebido());
        tv2.calcular();
        System.out.println();
        System.out.println();

        System.out.println("-".repeat(50));
        System.out.println("Problema GLICOSE");
        System.out.println("-".repeat(50));
        System.out.println("Exemplo 1:");
        Glicose g1 = new Glicose();
        g1.setMedida(90.0);
        System.out.printf("Digite a medida da glicose: %.1f%n", g1.getMedida());
        System.out.printf("Classificacao: %s%n", g1.getClassificacao());
        System.out.println();
        System.out.println("Exemplo 2:");
        Glicose g2 = new Glicose();
        g2.setMedida(140.0);
        System.out.printf("Digite a medida da glicose: %.1f%n", g2.getMedida());
        System.out.printf("Classificacao: %s%n", g2.getClassificacao());
        System.out.println();
        System.out.println("Exemplo 3:");
        Glicose g3 = new Glicose();
        g3.setMedida(143.2);
        System.out.printf("Digite a medida da glicose: %.1f%n", g3.getMedida());
        System.out.printf("Classificacao: %s%n", g3.getClassificacao());
        System.out.println();

        System.out.println("-".repeat(50));
        System.out.println("Problema DARDO");
        System.out.println("-".repeat(50));
        System.out.println("Exemplo 1:");
        Dardo dart1 = new Dardo();
        dart1.setD1(83.21);
        dart1.setD2(79.53);
        dart1.setD3(89.15);
        System.out.println("Digite as tres distancias:");
        System.out.printf("%.2f%n", dart1.getD1());
        System.out.printf("%.2f%n", dart1.getD2());
        System.out.printf("%.2f%n", dart1.getD3());
        System.out.printf("MAIOR DISTANCIA = %.2f%n", dart1.getMaiorDistancia());
        System.out.println();
        System.out.println("Exemplo 2:");
        Dardo dart2 = new Dardo();
        dart2.setD1(83.21);
        dart2.setD2(87.20);
        dart2.setD3(83.21);
        System.out.println("Digite as tres distancias:");
        System.out.printf("%.2f%n", dart2.getD1());
        System.out.printf("%.2f%n", dart2.getD2());
        System.out.printf("%.2f%n", dart2.getD3());
        System.out.printf("MAIOR DISTANCIA = %.2f%n", dart2.getMaiorDistancia());
        System.out.println();

        System.out.println("-".repeat(50));
        System.out.println("Problema TEMPERATURA");
        System.out.println("-".repeat(50));
        System.out.println("Exemplo 1:");
        Temperatura temp1 = new Temperatura();
        temp1.setTemp(75.00);
        System.out.println("Voce vai digitar a temperatura em qual escala (C/F)? F");
        System.out.printf("Digite a temperatura em Fahrenheit: %.2f%n", temp1.getTemp());
        System.out.printf("Temperatura equivalente em Celsius: %.2f%n", temp1.getTempInCelsius());
        System.out.println();
        System.out.println("Exemplo 2:");
        Temperatura temp2 = new Temperatura();
        temp2.setTemp(28.15);
        System.out.println("Voce vai digitar a temperatura em qual escala (C/F)? C");
        System.out.printf("Digite a temperatura em Celsius: %.2f%n", temp2.getTemp());
        System.out.printf("Temperatura equivalente em Fahrenheit: %.2f%n", temp2.getTempInFahrenheit());
        System.out.println();

        System.out.println("-".repeat(50));
        System.out.println("Problema LANCHONETE");
        System.out.println("-".repeat(50));
        System.out.println("Exemplo 1:");
        Lanchonete l1 = new Lanchonete();
        l1.setCodigoProduto(1);
        l1.setQtdProduto(3);
        System.out.printf("Codigo do produto comprado: %d%n", l1.getCodigoProduto());
        System.out.printf("Quantidade comprada: %d%n", l1.getQtdProduto());
        System.out.printf("Valor a pagar: R$ %.2f%n", l1.getTotal());
        System.out.println();
        System.out.println("Exemplo 2:");
        Lanchonete l2 = new Lanchonete();
        l2.setCodigoProduto(4);
        l2.setQtdProduto(2);
        System.out.printf("Codigo do produto comprado: %d%n", l2.getCodigoProduto());
        System.out.printf("Quantidade comprada: %d%n", l2.getQtdProduto());
        System.out.printf("Valor a pagar: R$ %.2f%n", l2.getTotal());
        System.out.println();

        System.out.println("-".repeat(50));
        System.out.println("Problema MULTIPLOS");
        System.out.println("-".repeat(50));
        System.out.println("Exemplo 1:");
        Multiplos mult1 = new Multiplos();
        mult1.setN1(6);
        mult1.setN2(24);
        System.out.println("Digite dois numeros inteiros:");
        System.out.printf("%d%n", mult1.getN1());
        System.out.printf("%d%n", mult1.getN2());
        System.out.println(mult1.isMultiplos() ? "Sao multiplos" : "Nao sao multiplos");
        System.out.println();
        System.out.println("Exemplo 2:");
        Multiplos mult2 = new Multiplos();
        mult2.setN1(24);
        mult2.setN2(6);
        System.out.println("Digite dois numeros inteiros:");
        System.out.printf("%d%n", mult2.getN1());
        System.out.printf("%d%n", mult2.getN2());
        System.out.println(mult2.isMultiplos() ? "Sao multiplos" : "Nao sao multiplos");
        System.out.println();
        System.out.println("Exemplo 3:");
        Multiplos mult3 = new Multiplos();
        mult3.setN1(13);
        mult3.setN2(5);
        System.out.println("Digite dois numeros inteiros:");
        System.out.printf("%d%n", mult3.getN1());
        System.out.printf("%d%n", mult3.getN2());
        System.out.println(mult3.isMultiplos() ? "Sao multiplos" : "Nao sao multiplos");
        System.out.println();

        System.out.println("-".repeat(50));
        System.out.println("Problema AUMENTO");
        System.out.println("-".repeat(50));
        System.out.println("Exemplo 1:");
        Aumento aum1 = new Aumento();
        aum1.setSalario(new BigDecimal("2500.00"));
        System.out.printf("Digite o salario da pessoa: %.2f%n", aum1.getSalario());
        System.out.printf("Novo salario = R$ %.2f%n", aum1.getNovoSalario());
        System.out.printf("Aumento = R$ %.2f%n", aum1.getAumento());
        System.out.printf("Porcentagem = %.0f %% %n", aum1.getPorcentagemAumento());
        System.out.println();
        System.out.println("Exemplo 2:");
        Aumento aum2 = new Aumento();
        aum2.setSalario(new BigDecimal("8000.00"));
        System.out.printf("Digite o salario da pessoa: %.2f%n", aum2.getSalario());
        System.out.printf("Novo salario = R$ %.2f%n", aum2.getNovoSalario());
        System.out.printf("Aumento = R$ %.2f%n", aum2.getAumento());
        System.out.printf("Porcentagem = %.0f %% %n", aum2.getPorcentagemAumento());
        System.out.println();

        System.out.println("-".repeat(50));
        System.out.println("Problema TEMPO_DE_JOGO");
        System.out.println("-".repeat(50));
        System.out.println("Exemplo 1:");
        TempoDeJogo tj1 = new TempoDeJogo();
        tj1.setHoraInicial(16);
        tj1.setHoraFinal(2);
        System.out.printf("Hora inicial: %d%n", tj1.getHoraInicial());
        System.out.printf("Hora final: %d%n", tj1.getHoraFinal());
        System.out.printf("O JOGO DUROU %d HORA(S)%n", tj1.getTotalHoras());
        System.out.println();
        System.out.println("Exemplo 2:");
        TempoDeJogo tj2 = new TempoDeJogo();
        tj2.setHoraInicial(0);
        tj2.setHoraFinal(0);
        System.out.printf("Hora inicial: %d%n", tj2.getHoraInicial());
        System.out.printf("Hora final: %d%n", tj2.getHoraFinal());
        System.out.printf("O JOGO DUROU %d HORA(S)%n", tj2.getTotalHoras());
        System.out.println();
        System.out.println("Exemplo 3:");
        TempoDeJogo tj3 = new TempoDeJogo();
        tj3.setHoraInicial(2);
        tj3.setHoraFinal(16);
        System.out.printf("Hora inicial: %d%n", tj3.getHoraInicial());
        System.out.printf("Hora final: %d%n", tj3.getHoraFinal());
        System.out.printf("O JOGO DUROU %d HORA(S)%n", tj3.getTotalHoras());
        System.out.println();

        System.out.println("-".repeat(50));
        System.out.println("Problema COORDENADAS");
        System.out.println("-".repeat(50));
        System.out.println("Exemplo 1:");
        Coordenadas coord1 = new Coordenadas();
        coord1.setX(4.5);
        coord1.setY(-2.2);
        System.out.printf("Valor de X: %.1f%n", coord1.getX());
        System.out.printf("Valor de Y: %.1f%n", coord1.getY());
        System.out.println(coord1.getQuadrante());
        System.out.println();
        System.out.println("Exemplo 2:");
        Coordenadas coord2 = new Coordenadas();
        coord2.setX(3.1);
        coord2.setY(2.0);
        System.out.printf("Valor de X: %.1f%n", coord2.getX());
        System.out.printf("Valor de Y: %.1f%n", coord2.getY());
        System.out.println(coord2.getQuadrante());
        System.out.println();
        System.out.println("Exemplo 3:");
        Coordenadas coord3 = new Coordenadas();
        coord3.setX(0.0);
        coord3.setY(0.0);
        System.out.printf("Valor de X: %.1f%n", coord3.getX());
        System.out.printf("Valor de Y: %.1f%n", coord3.getY());
        System.out.println(coord3.getQuadrante());
        System.out.println();
        System.out.println("Exemplo 4:");
        Coordenadas coord4 = new Coordenadas();
        coord4.setX(3.8);
        coord4.setY(0.0);
        System.out.printf("Valor de X: %.1f%n", coord4.getX());
        System.out.printf("Valor de Y: %.1f%n", coord4.getY());
        System.out.println(coord4.getQuadrante());
        System.out.println();

        System.out.println("=".repeat(50));
        System.out.println("Curso Completo de Algoritmos e Logica de Programacao");
        System.out.println("educandoweb.com.br");
        System.out.println("Prof. Dr. Nelio Alves");
        System.out.println("Capitulo: Estruturas repetitivas");
        System.out.println("Exercicios - PARTE 3");
        System.out.println("=".repeat(50));
        System.out.println();

        System.out.println("-".repeat(50));
        System.out.println("Problema CRESCENTE");
        System.out.println("-".repeat(50));
        System.out.println("Exemplo 1:");
        Crescente cr1 = new Crescente();
        cr1.setN1(5);
        cr1.setN2(4);
        System.out.printf("Primeiro valor: %d%n", cr1.getN1());
        System.out.printf("Segundo valor: %d%n", cr1.getN2());
        System.out.println(cr1.getResultado());
        System.out.println();
        System.out.println("Exemplo 2:");
        Crescente cr2 = new Crescente();
        cr2.setN1(3);
        cr2.setN2(8);
        System.out.printf("Primeiro valor: %d%n", cr2.getN1());
        System.out.printf("Segundo valor: %d%n", cr2.getN2());
        System.out.println(cr2.getResultado());
        System.out.println();

        System.out.println("-".repeat(50));
        System.out.println("Problema MEDIA_IDADES");
        System.out.println("-".repeat(50));
        System.out.println("Exemplo 1:");
        MediaIdades mi1 = new MediaIdades();
        Double[] idades1 = { 31.0, 27.0, 46.0, -5.0 };
        System.out.println("Digite as idades:");
        System.out.println("31");
        System.out.println("27");
        System.out.println("46");
        System.out.println("-5");
        mi1.processar(idades1);
        System.out.printf("MEDIA = %.2f%n", mi1.getMedia());
        System.out.println();
        System.out.println("Exemplo 2:");
        MediaIdades mi2 = new MediaIdades();
        Double[] idades2 = { -10.0 };
        mi2.processar(idades2);
        if (mi2.isImpossivelCalcular()) {
            System.out.println("IMPOSSIVEL CALCULAR");
        } else {
            System.out.printf("MEDIA = %.2f%n", mi2.getMedia());
        }
        System.out.println();

        System.out.println("-".repeat(50));
        System.out.println("Problema SENHA_FIXA");
        System.out.println("-".repeat(50));
        System.out.println("Exemplo 1:");
        SenhaFixa sf1 = new SenhaFixa();
        System.out.println("Digite a senha: 2312");
        System.out.println(sf1.validar(2312) ? "Acesso permitido!" : "Senha Invalida! Tente novamente: 2010");
        System.out.println(sf1.validar(2010) ? "Acesso permitido!" : "Senha Invalida! Tente novamente: 1022");
        System.out.println(sf1.validar(1022) ? "Acesso permitido!" : "Senha Invalida! Tente novamente: 2002");
        System.out.println(sf1.validar(2002) ? "Acesso permitido!" : "Senha Invalida!");
        System.out.println();

        System.out.println("-".repeat(50));
        System.out.println("Problema QUADRANTE");
        System.out.println("-".repeat(50));
        System.out.println("Exemplo 1:");
        Quadrante q1 = new Quadrante();
        q1.setX(2.0);
        q1.setY(2.0);
        System.out.printf("Valor de X: %.1f%n", q1.getX());
        System.out.printf("Valor de Y: %.1f%n", q1.getY());
        System.out.println(q1.getQuadrante());
        System.out.println();
        System.out.println("Exemplo 2:");
        Quadrante q2 = new Quadrante();
        q2.setX(3.0);
        q2.setY(-2.0);
        System.out.printf("Valor de X: %.1f%n", q2.getX());
        System.out.printf("Valor de Y: %.1f%n", q2.getY());
        System.out.println(q2.getQuadrante());
        System.out.println();
        System.out.println("Exemplo 3:");
        Quadrante q3 = new Quadrante();
        q3.setX(-8.0);
        q3.setY(-1.0);
        System.out.printf("Valor de X: %.1f%n", q3.getX());
        System.out.printf("Valor de Y: %.1f%n", q3.getY());
        System.out.println(q3.getQuadrante());
        System.out.println();
        System.out.println("Exemplo 4:");
        Quadrante q4 = new Quadrante();
        q4.setX(-7.0);
        q4.setY(1.0);
        System.out.printf("Valor de X: %.1f%n", q4.getX());
        System.out.printf("Valor de Y: %.1f%n", q4.getY());
        System.out.println(q4.getQuadrante());
        System.out.println();

        System.out.println("-".repeat(50));
        System.out.println("Problema VALIDACAO_DE_NOTA");
        System.out.println("-".repeat(50));
        System.out.println("Exemplo 1:");
        ValidacaoDeNota vn1 = new ValidacaoDeNota();
        vn1.setNota1(3.5);
        vn1.setNota2(10.0);
        System.out.printf("Digite a primeira nota: %.1f%n", vn1.getNota1());
        System.out.printf("Digite a segunda nota: %.1f%n", vn1.getNota2());
        System.out.printf("MEDIA = %.2f%n", vn1.getMedia());
        System.out.println();
        System.out.println("Exemplo 2:");
        ValidacaoDeNota vn2 = new ValidacaoDeNota();
        vn2.setNota1(3.5);
        vn2.setNota2(10.0);
        System.out.println("Digite a primeira nota: -3.5");
        System.out.println("Valor invalido! Tente novamente: 3.5");
        System.out.printf("Digite a primeira nota: %.1f%n", vn2.getNota1());
        System.out.println("Digite a segunda nota: 11.0");
        System.out.println("Valor invalido! Tente novamente: 10.5");
        System.out.println("Valor invalido! Tente novamente: 10.0");
        System.out.printf("Digite a segunda nota: %.1f%n", vn2.getNota2());
        System.out.printf("MEDIA = %.2f%n", vn2.getMedia());
        System.out.println();

        System.out.println("-".repeat(50));
        System.out.println("Problema COMBUSTIVEL");
        System.out.println("-".repeat(50));
        System.out.println("Exemplo 1:");
        Combustivel cb1 = new Combustivel();
        Integer[] codigos1 = { 1, 2, 2 };
        System.out.println("Informe um codigo (1, 2, 3) ou 4 para parar: 8");
        System.out.println("Informe um codigo (1, 2, 3) ou 4 para parar: 1");
        System.out.println("Informe um codigo (1, 2, 3) ou 4 para parar: 7");
        System.out.println("Informe um codigo (1, 2, 3) ou 4 para parar: 2");
        System.out.println("Informe um codigo (1, 2, 3) ou 4 para parar: 2");
        System.out.println("Informe um codigo (1, 2, 3) ou 4 para parar: 4");
        for (Integer c : codigos1) {
            cb1.registrar(c);
        }
        System.out.println("MUITO OBRIGADO");
        System.out.println("Alcool: " + cb1.getAlcool());
        System.out.println("Gasolina: " + cb1.getGasolina());
        System.out.println("Diesel: " + cb1.getDiesel());
        System.out.println();

        System.out.println("-".repeat(50));
        System.out.println("Problema PARES_CONSECUTIVOS");
        System.out.println("-".repeat(50));
        System.out.println("Exemplo 1:");
        ParesConsecutivos pc1 = new ParesConsecutivos();
        pc1.setValor(4);
        System.out.printf("Digite um numero inteiro: %d%n", pc1.getValor());
        System.out.println("SOMA = " + pc1.getSoma());
        System.out.println();
        System.out.println("Exemplo 2:");
        ParesConsecutivos pc2 = new ParesConsecutivos();
        pc2.setValor(11);
        System.out.printf("Digite um numero inteiro: %d%n", pc2.getValor());
        System.out.println("SOMA = " + pc2.getSoma());
        System.out.println();
        System.out.println("Exemplo 3:");
        ParesConsecutivos pc3 = new ParesConsecutivos();
        pc3.setValor(0);
        System.out.printf("Digite um numero inteiro: %d%n", pc3.getValor());
        System.out.println();

        System.out.println("-".repeat(50));
        System.out.println("Problema TABUADA");
        System.out.println("-".repeat(50));
        System.out.println("Exemplo 1:");
        Tabuada tab1 = new Tabuada();
        tab1.setN(4);
        System.out.printf("Deseja a tabuada para qual valor? %d%n", tab1.getN());
        for (Integer i = 1; i <= 10; i++) {
            System.out.printf("%d x %d = %d%n", tab1.getN(), i, tab1.getN() * i);
        }
        System.out.println();

        System.out.println("-".repeat(50));
        System.out.println("Problema SOMA_IMPARES");
        System.out.println("-".repeat(50));
        System.out.println("Exemplo 1:");
        SomaImpares si1 = new SomaImpares();
        si1.setX(2);
        si1.setY(9);
        System.out.println("Digite dois numeros:");
        System.out.printf("%d%n", si1.getX());
        System.out.printf("%d%n", si1.getY());
        System.out.println("SOMA DOS IMPARES = " + si1.getSoma());
        System.out.println();
        System.out.println("Exemplo 2:");
        SomaImpares si2 = new SomaImpares();
        si2.setX(15);
        si2.setY(10);
        System.out.println("Digite dois numeros:");
        System.out.printf("%d%n", si2.getX());
        System.out.printf("%d%n", si2.getY());
        System.out.println("SOMA DOS IMPARES = " + si2.getSoma());
        System.out.println();
        System.out.println("Exemplo 3:");
        SomaImpares si3 = new SomaImpares();
        si3.setX(6);
        si3.setY(-5);
        System.out.println("Digite dois numeros:");
        System.out.printf("%d%n", si3.getX());
        System.out.printf("%d%n", si3.getY());
        System.out.println("SOMA DOS IMPARES = " + si3.getSoma());
        System.out.println();

        System.out.println("-".repeat(50));
        System.out.println("Problema SEQUENCIA_IMPARES");
        System.out.println("-".repeat(50));
        System.out.println("Exemplo 1:");
        SequenciaImpares si4 = new SequenciaImpares();
        si4.setX(8);
        System.out.printf("Digite o valor de X: %d%n", si4.getX());
        System.out.println("1");
        System.out.println("3");
        System.out.println("5");
        System.out.println("7");
        System.out.println();

        System.out.println("-".repeat(50));
        System.out.println("Problema DENTRO_FORA");
        System.out.println("-".repeat(50));
        System.out.println("Exemplo 1:");
        DentroFora df1 = new DentroFora();
        System.out.println("Quantos numeros voce vai digitar? 5");
        Integer[] nums1 = { 14, 35, 10, 131, 8 };
        df1.processar(nums1);
        System.out.println("Digite um numero: 14");
        System.out.println("Digite um numero: 35");
        System.out.println("Digite um numero: 10");
        System.out.println("Digite um numero: 131");
        System.out.println("Digite um numero: 8");
        System.out.println(df1.getDentro() + " DENTRO");
        System.out.println(df1.getFora() + " FORA");
        System.out.println();

        System.out.println("-".repeat(50));
        System.out.println("Problema PAR_IMPAR");
        System.out.println("-".repeat(50));
        System.out.println("Exemplo 1:");
        ParImpar pi1 = new ParImpar();
        pi1.setNumero(-5);
        System.out.printf("Numero: %d%n", pi1.getNumero());
        System.out.println(pi1.getClassificacao());
        System.out.println();
        System.out.println("Exemplo 2:");
        ParImpar pi2 = new ParImpar();
        pi2.setNumero(0);
        System.out.printf("Numero: %d%n", pi2.getNumero());
        System.out.println(pi2.getClassificacao());
        System.out.println();
        System.out.println("Exemplo 3:");
        ParImpar pi3 = new ParImpar();
        pi3.setNumero(3);
        System.out.printf("Numero: %d%n", pi3.getNumero());
        System.out.println(pi3.getClassificacao());
        System.out.println();
        System.out.println("Exemplo 4:");
        ParImpar pi4 = new ParImpar();
        pi4.setNumero(-4);
        System.out.printf("Numero: %d%n", pi4.getNumero());
        System.out.println(pi4.getClassificacao());
        System.out.println();

        System.out.println("-".repeat(50));
        System.out.println("Problema MEDIA_PONDERADA");
        System.out.println("-".repeat(50));
        System.out.println("Exemplo 1:");
        MediaPonderada mp1 = new MediaPonderada();
        System.out.println("Quantos casos voce vai digitar? 3");
        System.out.println("Digite tres numeros:");
        System.out.println("6.5");
        System.out.println("4.3");
        System.out.println("6.2");
        System.out.printf("MEDIA = %.1f%n", mp1.calcularMedia(6.5, 4.3, 6.2));
        System.out.println();
        System.out.println("Exemplo 2:");
        MediaPonderada mp2 = new MediaPonderada();
        System.out.println("Digite tres numeros:");
        System.out.println("5.1");
        System.out.println("4.2");
        System.out.println("8.1");
        System.out.printf("MEDIA = %.1f%n", mp2.calcularMedia(5.1, 4.2, 8.1));
        System.out.println();
        System.out.println("Exemplo 3:");
        MediaPonderada mp3 = new MediaPonderada();
        System.out.println("Digite tres numeros:");
        System.out.println("8.0");
        System.out.println("9.0");
        System.out.println("10.0");
        System.out.printf("MEDIA = %.1f%n", mp3.calcularMedia(8.0, 9.0, 10.0));
        System.out.println();

        System.out.println("-".repeat(50));
        System.out.println("Problema DIVISAO");
        System.out.println("-".repeat(50));
        System.out.println("Exemplo 1:");
        Divisao div1 = new Divisao();
        div1.setNumerador(3.0);
        div1.setDenominador(-2.0);
        System.out.printf("Entre com o numerador: %.1f%n", div1.getNumerador());
        System.out.printf("Entre com o denominador: %.1f%n", div1.getDenominador());
        System.out.printf("DIVISAO = %.2f%n", div1.getDivisao());
        System.out.println();
        System.out.println("Exemplo 2:");
        Divisao div2 = new Divisao();
        div2.setNumerador(-8.0);
        div2.setDenominador(0.0);
        System.out.printf("Entre com o numerador: %.1f%n", div2.getNumerador());
        System.out.printf("Entre com o denominador: %.1f%n", div2.getDenominador());
        System.out.println("DIVISAO IMPOSSIVEL");
        System.out.println();
        System.out.println("Exemplo 3:");
        Divisao div3 = new Divisao();
        div3.setNumerador(0.0);
        div3.setDenominador(8.0);
        System.out.printf("Entre com o numerador: %.1f%n", div3.getNumerador());
        System.out.printf("Entre com o denominador: %.1f%n", div3.getDenominador());
        System.out.printf("DIVISAO = %.2f%n", div3.getDivisao());
        System.out.println();

        System.out.println("-".repeat(50));
        System.out.println("Problema FATORIAL");
        System.out.println("-".repeat(50));
        System.out.println("Exemplo 1:");
        Fatorial f1 = new Fatorial();
        f1.setN(4);
        System.out.printf("Digite o valor de N: %d%n", f1.getN());
        System.out.println("FATORIAL = " + f1.calcularFatorial());
        System.out.println();
        System.out.println("Exemplo 2:");
        Fatorial f2 = new Fatorial();
        f2.setN(0);
        System.out.printf("Digite o valor de N: %d%n", f2.getN());
        System.out.println("FATORIAL = " + f2.calcularFatorial());
        System.out.println();
        System.out.println("Exemplo 3:");
        Fatorial f3 = new Fatorial();
        f3.setN(6);
        System.out.printf("Digite o valor de N: %d%n", f3.getN());
        System.out.println("FATORIAL = " + f3.calcularFatorial());
        System.out.println();
        System.out.println("Exemplo 4:");
        Fatorial f4 = new Fatorial();
        f4.setN(1);
        System.out.printf("Digite o valor de N: %d%n", f4.getN());
        System.out.println("FATORIAL = " + f4.calcularFatorial());
        System.out.println();

        System.out.println("-".repeat(50));
        System.out.println("Problema EXPERIENCIAS");
        System.out.println("-".repeat(50));
        System.out.println("Exemplo 1:");
        System.out.println("Quantos casos de teste serao digitados? 10");
        System.out.println("Quantidade de cobaias: 10");
        System.out.println("Tipo de cobaia: C");
        System.out.println("Quantidade de cobaias: 6");
        System.out.println("Tipo de cobaia: R");
        System.out.println("Quantidade de cobaias: 15");
        System.out.println("Tipo de cobaia: S");
        System.out.println("Quantidade de cobaias: 5");
        System.out.println("Tipo de cobaia: C");
        System.out.println("Quantidade de cobaias: 14");
        System.out.println("Tipo de cobaia: R");
        System.out.println("Quantidade de cobaias: 9");
        System.out.println("Tipo de cobaia: C");
        System.out.println("Quantidade de cobaias: 6");
        System.out.println("Tipo de cobaia: R");
        System.out.println("Quantidade de cobaias: 8");
        System.out.println("Tipo de cobaia: S");
        System.out.println("Quantidade de cobaias: 5");
        System.out.println("Tipo de cobaia: C");
        System.out.println("Quantidade de cobaias: 14");
        System.out.println("Tipo de cobaia: R");
        Experiencias e1 = new Experiencias();
        Integer[] quantities = { 10, 6, 15, 5, 14, 9, 6, 8, 5, 14 };
        String[] types = { "C", "R", "S", "C", "R", "C", "R", "S", "C", "R" };
        e1.setN(10);
        e1.processarCobaias(quantities, types);
        e1.imprimirRelatorio();
        System.out.println();

        System.out.println("=".repeat(50));
        System.out.println("Curso Completo de Algoritmos e Logica de Programacao");
        System.out.println("educandoweb.com.br");
        System.out.println("Prof. Dr. Nelio Alves");
        System.out.println("Capitulo: Vetores");
        System.out.println("Exercicios - PARTE 4");
        System.out.println("=".repeat(50));
        System.out.println();

        System.out.println("-".repeat(50));
        System.out.println("Problema NEGATIVOS");
        System.out.println("-".repeat(50));
        System.out.println("Exemplo 1:");
        Negativos neg1 = new Negativos();
        Integer[] numsNeg1 = { 8, -2, 9, 10, -3, -7 };
        neg1.setNumeros(List.of(numsNeg1));
        System.out.println("Quantos numeros voce vai digitar? 6");
        for (Integer num : numsNeg1) {
            System.out.printf("Digite um numero: %d\n", num);
        }
        System.out.println("NUMEROS NEGATIVOS:");
        for (Integer num : neg1.getNumerosNegativos()) {
            System.out.println(num);
        }
        System.out.println();

        System.out.println("-".repeat(50));
        System.out.println("Problema SOMA_VETOR");
        System.out.println("-".repeat(50));
        System.out.println("Exemplo 1:");
        SomaVetor sv1 = new SomaVetor();
        Double[] numsSv1 = { 8.0, 4.0, 10.0, 14.0 };
        sv1.setNumeros(List.of(numsSv1));
        System.out.println("Quantos numeros voce vai digitar? 4");
        for (Double num : numsSv1) {
            System.out.printf("Digite um numero: %.1f\n", num);
        }
        System.out.print("VALORES = ");
        for (Double num : sv1.getNumeros()) {
            System.out.printf("%.1f ", num);
        }
        System.out.println();
        System.out.printf("SOMA = %.2f\n", sv1.getSoma());
        System.out.printf("MEDIA = %.2f\n", sv1.getMedia());
        System.out.println();

        System.out.println("-".repeat(50));
        System.out.println("Problema ALTURAS");
        System.out.println("-".repeat(50));
        System.out.println("Exemplo 1:");
        Alturas alt1 = new Alturas();
        String[] nomesAlt = { "Joao", "Maria", "Teresa", "Carlos", "Paulo" };
        Integer[] idadesAlt = { 15, 16, 14, 21, 17 };
        Double[] alturasAlt = { 1.82, 1.60, 1.58, 1.65, 1.78 };
        alt1.setNomes(List.of(nomesAlt));
        alt1.setIdades(List.of(idadesAlt));
        alt1.setAlturas(List.of(alturasAlt));
        System.out.println("Quantas pessoas serao digitadas? 5");
        for (int i = 0; i < 5; i++) {
            System.out.printf("Dados da %da pessoa:\n", i + 1);
            System.out.printf("Nome: %s\n", nomesAlt[i]);
            System.out.printf("Idade: %d\n", idadesAlt[i]);
            System.out.printf("Altura: %.2f\n", alturasAlt[i]);
        }
        System.out.printf("Altura media: %.2f\n", alt1.getMedia());
        System.out.printf("Pessoas com menos de 16 anos: %.1f%%\n", alt1.getPorcentagemMenores());
        System.out.println("Nomes:");
        for (String nome : alt1.getNomesMenores()) {
            System.out.println(nome);
        }
        System.out.println();

        System.out.println("-".repeat(50));
        System.out.println("Problema NUMEROS_PARES");
        System.out.println("-".repeat(50));
        System.out.println("Exemplo 1:");
        NumerosPares np1 = new NumerosPares();
        Integer[] numsNp1 = { 8, 2, 11, 14, 13, 20 };
        np1.setNumeros(List.of(numsNp1));
        System.out.println("Quantos numeros voce vai digitar? 6");
        for (Integer num : numsNp1) {
            System.out.printf("Digite um numero: %d\n", num);
        }
        System.out.println("NUMEROS PARES:");
        for (Integer num : np1.getNumerosPares()) {
            System.out.print(num + " ");
        }
        System.out.println();
        System.out.println("QUANTIDADE DE PARES = " + np1.getQtdPares());
        System.out.println();

        System.out.println("-".repeat(50));
        System.out.println("Problema MAIOR_POSICAO");
        System.out.println("-".repeat(50));
        System.out.println("Exemplo 1:");
        MaiorPosicao mpVetor1 = new MaiorPosicao();
        Double[] numsMp1 = { 8.0, 4.0, 10.0, 14.0, 13.0, 7.0 };
        mpVetor1.setNumeros(List.of(numsMp1));
        System.out.println("Quanto numeros voce vai digitar? 6");
        for (Double num : numsMp1) {
            System.out.printf("Digite um numero: %.1f\n", num);
        }
        System.out.printf("MAIOR VALOR = %.1f\n", mpVetor1.getMaior());
        System.out.println("POSICAO DO MAIOR VALOR = " + mpVetor1.getMaiorIndex());
        System.out.println();

        System.out.println("-".repeat(50));
        System.out.println("Problema SOMA_VETORES");
        System.out.println("-".repeat(50));
        System.out.println("Exemplo 1:");
        SomaVetores svs1 = new SomaVetores();
        Integer[] vetorA = { 8, 2, 11, 14, 13, 20 };
        Integer[] vetorB = { 5, 10, 3, 1, 10, 7 };
        svs1.setA(List.of(vetorA));
        svs1.setB(List.of(vetorB));
        System.out.println("Quantos valores vai ter cada vetor? 6");
        System.out.println("Digite os valores do vetor A:");
        for (Integer num : vetorA) {
            System.out.println(num);
        }
        System.out.println("Digite os valores do vetor B:");
        for (Integer num : vetorB) {
            System.out.println(num);
        }
        System.out.println("VETOR RESULTANTE:");
        for (Integer num : svs1.getVetorResultante()) {
            System.out.println(num);
        }
        System.out.println();

        System.out.println("-".repeat(50));
        System.out.println("Problema ABAIXO_DA_MEDIA");
        System.out.println("-".repeat(50));
        System.out.println("Exemplo 1:");
        AbaixoDaMedia am1 = new AbaixoDaMedia();
        Double[] numsAm1 = { 10.0, 15.5, 13.2, 9.8 };
        am1.setNumeros(List.of(numsAm1));
        System.out.println("Quantos elementos vai ter o vetor? 4");
        for (Double num : numsAm1) {
            System.out.printf("Digite um numero: %.1f\n", num);
        }
        System.out.printf("MEDIA DO VETOR = %.3f\n", am1.getMedia());
        System.out.println("ELEMENTOS ABAIXO DA MEDIA:");
        for (Double num : am1.getAbaixoMedia()) {
            System.out.printf("%.1f\n", num);
        }
        System.out.println();

        System.out.println("-".repeat(50));
        System.out.println("Problema MEDIA_PARES");
        System.out.println("-".repeat(50));
        System.out.println("Exemplo 1:");
        MediaPares mpar1 = new MediaPares();
        Integer[] numsMpar1 = { 8, 2, 11, 14, 13, 20 };
        mpar1.setNumeros(List.of(numsMpar1));
        System.out.println("Quantos elementos vai ter o vetor? 6");
        for (Integer num : numsMpar1) {
            System.out.printf("Digite um numero: %d\n", num);
        }
        if (mpar1.getTotalPares() > 0) {
            System.out.printf("MEDIA DOS PARES = %.1f\n", mpar1.getMediaPares());
        } else {
            System.out.println("NENHUM NUMERO PAR");
        }
        System.out.println();
        System.out.println("Exemplo 2:");
        MediaPares mpar2 = new MediaPares();
        Integer[] numsMpar2 = { 7, 9, 11 };
        mpar2.setNumeros(List.of(numsMpar2));
        System.out.println("Quantos elementos vai ter o vetor? 3");
        for (Integer num : numsMpar2) {
            System.out.printf("Digite um numero: %d\n", num);
        }
        if (mpar2.getTotalPares() > 0) {
            System.out.printf("MEDIA DOS PARES = %.1f\n", mpar2.getMediaPares());
        } else {
            System.out.println("NENHUM NUMERO PAR");
        }
        System.out.println();

        System.out.println("-".repeat(50));
        System.out.println("Problema MAIS_VELHO");
        System.out.println("-".repeat(50));
        System.out.println("Exemplo 1:");
        MaisVelho mv1 = new MaisVelho();
        String[] nomesMv = { "Joao", "Maria", "Teresa", "Carlos", "Paulo" };
        Integer[] idadesMv = { 16, 21, 15, 23, 17 };
        mv1.setNomes(List.of(nomesMv));
        mv1.setIdades(List.of(idadesMv));
        System.out.println("Quantas pessoas voce vai digitar? 5");
        for (int i = 0; i < 5; i++) {
            System.out.printf("Dados da %da pessoa:\n", i + 1);
            System.out.printf("Nome: %s\n", nomesMv[i]);
            System.out.printf("Idade: %d\n", idadesMv[i]);
        }
        System.out.println("PESSOA MAIS VELHA: " + mv1.getNomeMaisVelho());
        System.out.println();

        System.out.println("-".repeat(50));
        System.out.println("Problema APROVADOS");
        System.out.println("-".repeat(50));
        System.out.println("Exemplo 1:");
        Aprovados ap1 = new Aprovados();
        String[] alunosAp = { "Joao Silva", "Maria Teixeira", "Carlos Carvalho", "Teresa Pires" };
        Double[] notas1Ap = { 7.0, 9.2, 5.0, 5.5 };
        Double[] notas2Ap = { 8.5, 6.5, 6.0, 6.5 };
        ap1.setAlunos(List.of(alunosAp));
        ap1.setNotas1(List.of(notas1Ap));
        ap1.setNotas2(List.of(notas2Ap));
        System.out.println("Quantos alunos serao digitados? 4");
        for (int i = 0; i < 4; i++) {
            System.out.printf("Digite nome, primeira e segunda nota do %do aluno:\n", i + 1);
            System.out.println(alunosAp[i]);
            System.out.println(notas1Ap[i]);
            System.out.println(notas2Ap[i]);
        }
        System.out.println("Alunos aprovados:");
        for (String aluno : ap1.getAprovados()) {
            System.out.println(aluno);
        }
        System.out.println();

        System.out.println("-".repeat(50));
        System.out.println("Problema DADOS_PESSOAS");
        System.out.println("-".repeat(50));
        System.out.println("Exemplo 1:");
        DadosPessoas dp1 = new DadosPessoas();
        Double[] alturasDp = { 1.70, 1.83, 1.54, 1.61, 1.75 };
        String[] generosDp = { "F", "M", "M", "F", "F" };
        dp1.setAlturas(List.of(alturasDp));
        dp1.setGeneros(List.of(generosDp));
        System.out.println("Quantas pessoas serao digitadas? 5");
        for (int i = 0; i < 5; i++) {
            System.out.printf("Altura da %da pessoa: %.2f\n", i + 1, alturasDp[i]);
            System.out.printf("Genero da %da pessoa: %s\n", i + 1, generosDp[i]);
        }
        System.out.printf("Menor altura = %.2f\n", dp1.getMenorAltura());
        System.out.printf("Maior altura = %.2f\n", dp1.getMaiorAltura());
        System.out.printf("Media das alturas das mulheres = %.2f\n", dp1.getMediaAlturaMulheres());
        System.out.println("Numero de homens = " + dp1.getTotalHomens());
        System.out.println();

        System.out.println("-".repeat(50));
        System.out.println("Problema COMERCIANTE");
        System.out.println("-".repeat(50));
        System.out.println("Exemplo 1:");
        Comerciante com1 = new Comerciante();
        String[] produtosCom = { "Feijao", "Arroz", "Oleo", "Sal" };
        BigDecimal[] compraCom = { new BigDecimal("10.00"), new BigDecimal("12.00"), new BigDecimal("5.00"), new BigDecimal("3.00") };
        BigDecimal[] vendaCom = { new BigDecimal("11.00"), new BigDecimal("12.80"), new BigDecimal("5.70"), new BigDecimal("4.00") };
        com1.setProdutos(List.of(produtosCom));
        com1.setPrecosCompra(List.of(compraCom));
        com1.setPrecosVenda(List.of(vendaCom));
        System.out.println("Serao digitados dados de quantos produtos? 4");
        for (int i = 0; i < 4; i++) {
            System.out.printf("Produto %d:\n", i + 1);
            System.out.println("Nome: " + produtosCom[i]);
            System.out.printf("Preco de compra: %.2f\n", compraCom[i]);
            System.out.printf("Preco de venda: %.2f\n", vendaCom[i]);
        }
        System.out.println("\nRELATORIO:");
        System.out.println("Lucro abaixo de 10%: " + com1.getLucroBaixo());
        System.out.println("Lucro entre 10% e 20%: " + com1.getLucroMedio());
        System.out.println("Lucro acima de 20%: " + com1.getLucroAlto());
        System.out.printf("Valor total de compra: %.2f\n", com1.getTotalCompra());
        System.out.printf("Valor total de venda: %.2f\n", com1.getTotalVenda());
        System.out.printf("Lucro total: %.2f\n", com1.getTotalLucro());
        System.out.println();

        System.out.println("=".repeat(50));
        System.out.println("TODOS OS TESTES EXECUTADOS COM SUCESSO!");
        System.out.println("=".repeat(50));
    }
}